"""empty message

Revision ID: 1a9819262e08
Revises: cae4e6068f03
Create Date: 2019-07-06 13:27:42.613208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a9819262e08'
down_revision = 'cae4e6068f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pay_order', 'note',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('pay_order', 'prepay_id',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pay_order', 'prepay_id',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('pay_order', 'note',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
