"""empty message

Revision ID: 39986f42e7e0
Revises: 5150aae4f48b
Create Date: 2019-07-05 11:27:07.165318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39986f42e7e0'
down_revision = '5150aae4f48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'comment_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('food', 'total_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('food', 'view_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'view_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('food', 'total_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('food', 'comment_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
