"""empty message

Revision ID: 63e1652d568e
Revises: b12d1a73e7b1
Create Date: 2019-07-04 10:51:08.164930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e1652d568e'
down_revision = 'b12d1a73e7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###
