"""empty message

Revision ID: 9710b05eb797
Revises: 879654f493b8
Create Date: 2019-07-06 13:35:41.328589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9710b05eb797'
down_revision = '879654f493b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pay_order', 'comment_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('pay_order', 'pay_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pay_order', 'pay_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pay_order', 'comment_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
