"""empty message

Revision ID: aa7e6fd1932f
Revises: abcfaf4cc781
Create Date: 2019-07-06 12:33:03.846673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7e6fd1932f'
down_revision = 'abcfaf4cc781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=600), nullable=False),
    sa.Column('expired_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_access_token_expired_time'), 'oauth_access_token', ['expired_time'], unique=False)
    op.create_table('pay_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(length=40), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yun_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_sn', sa.String(length=128), nullable=False),
    sa.Column('prepay_id', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('express_status', sa.Integer(), nullable=False),
    sa.Column('express_address_id', sa.Integer(), nullable=False),
    sa.Column('express_info', sa.String(length=100), nullable=False),
    sa.Column('comment_status', sa.Integer(), nullable=False),
    sa.Column('pay_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_sn')
    )
    op.create_index('idx_member_id_status', 'pay_order', ['member_id', 'status'], unique=False)
    op.create_table('pay_order_callback_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_order_id', sa.Integer(), nullable=False),
    sa.Column('pay_data', sa.Text(), nullable=False),
    sa.Column('refund_data', sa.Text(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pay_order_id')
    )
    op.create_table('pay_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_order_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_order_item_food_id'), 'pay_order_item', ['food_id'], unique=False)
    op.create_index(op.f('ix_pay_order_item_pay_order_id'), 'pay_order_item', ['pay_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_order_item_pay_order_id'), table_name='pay_order_item')
    op.drop_index(op.f('ix_pay_order_item_food_id'), table_name='pay_order_item')
    op.drop_table('pay_order_item')
    op.drop_table('pay_order_callback_data')
    op.drop_index('idx_member_id_status', table_name='pay_order')
    op.drop_table('pay_order')
    op.drop_index(op.f('ix_oauth_access_token_expired_time'), table_name='oauth_access_token')
    op.drop_table('oauth_access_token')
    # ### end Alembic commands ###
