"""empty message

Revision ID: b12d1a73e7b1
Revises: b4630f7ce52b
Create Date: 2019-07-04 10:49:26.962142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b12d1a73e7b1'
down_revision = 'b4630f7ce52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
