"""empty message

Revision ID: bb43c1713922
Revises: 
Create Date: 2019-07-05 23:55:03.750214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb43c1713922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referer_url', sa.String(length=255), nullable=True),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=False),
    sa.Column('ua', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referer_url', sa.String(length=255), nullable=True),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('main_image', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=10000), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('month_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('food_sale_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_sale_change_log_food_id'), 'food_sale_change_log', ['food_id'], unique=False)
    op.create_table('food_stock_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('total_stock', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_stock_change_log_food_id'), 'food_stock_change_log', ['food_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_key', sa.String(length=60), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=False),
    sa.Column('reg_ip', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_cart_member_id'), 'member_cart', ['member_id'], unique=False)
    op.create_table('oauth_member_bind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=80), nullable=False),
    sa.Column('unionid', sa.String(length=100), nullable=True),
    sa.Column('extra', sa.Text(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type_openid', 'oauth_member_bind', ['type', 'openid'], unique=False)
    op.create_table('user',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('login_name', sa.String(length=20), nullable=False),
    sa.Column('login_pwd', sa.String(length=32), nullable=False),
    sa.Column('login_salt', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('login_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('idx_type_openid', table_name='oauth_member_bind')
    op.drop_table('oauth_member_bind')
    op.drop_index(op.f('ix_member_cart_member_id'), table_name='member_cart')
    op.drop_table('member_cart')
    op.drop_table('member')
    op.drop_table('images')
    op.drop_index(op.f('ix_food_stock_change_log_food_id'), table_name='food_stock_change_log')
    op.drop_table('food_stock_change_log')
    op.drop_index(op.f('ix_food_sale_change_log_food_id'), table_name='food_sale_change_log')
    op.drop_table('food_sale_change_log')
    op.drop_table('food_cat')
    op.drop_table('food')
    op.drop_table('app_error_log')
    op.drop_table('app_access_log')
    # ### end Alembic commands ###
