"""empty message

Revision ID: cc52c0ffc922
Revises: 63e1652d568e
Create Date: 2019-07-04 10:51:40.395774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc52c0ffc922'
down_revision = '63e1652d568e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
