"""empty message

Revision ID: cf0f896aee88
Revises: d45520efb74a
Create Date: 2019-07-04 10:53:41.910724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf0f896aee88'
down_revision = 'd45520efb74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
